drop procedure if exists`epoint_proc_alter`;
GO
create   procedure `epoint_proc_alter`()
begin
     if  (select count(1) from information_schema.tables where TABLE_SCHEMA=DATABASE() and table_name='portrait_tags_api_info')<1
     then
            CREATE TABLE `portrait_tags_api_info` (
                `rowguid` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '默认主键字段',
                `apiCategoryGuid` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'api分类guid',
                `serviceName` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '服务名称',
                `serviceDesc` text COLLATE utf8_bin COMMENT '服务描述',
                `serviceSource` int(11) DEFAULT NULL COMMENT '服务来源 0:系统服务 1:第三方 2.接口生成',
                `originalAddress` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '接口源地址',
                `requestMethod` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '请求方法 0:GET 1:POST 2:GET/POST',
                `contentType` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '请求内容类型',
                `requestSample` text COLLATE utf8_bin COMMENT '请求示例',
                `responseSample` text COLLATE utf8_bin COMMENT '响应实例',
                `gatewayServiceId` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '网关服务id',
                `gatewayServicePath` varchar(4000) COLLATE utf8_bin DEFAULT NULL COMMENT '网关服务路径',
                `gatewayServiceState` int(11) DEFAULT '0' COMMENT '网关服务状态 :0:未注册 1:已注册 2:已发布 3已下线',
                `gatewayproxyaccessurl` varchar(4000) COLLATE utf8_bin DEFAULT NULL COMMENT 'API网关代理访问地址',
                `product_id` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'APIG网关预留字段',
                `plan_id` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'APIG网关预留字段',
                `backend_id` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'APIG网关预留字段',
                `operation_id` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'APIG网关预留字段',
                `createDatetime` datetime DEFAULT NULL COMMENT '创建时间',
                `updateDatetime` datetime DEFAULT NULL COMMENT '更新时间',
                PRIMARY KEY (`rowguid`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
            INSERT INTO `portrait_tags_api_info` VALUES ('2a599083-b368-4619-83c1-5198b909a270', '4e026be2-a2aa-49f4-af1f-614070906a00', '主体所含标签列表查询服务', '获取目标主体下 当前部门拥有权限的标签的信息（拥有权限是指：当前部门为标签创建部门,或被授予标签权限的部门,或该标签本就是共有标签)', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n               \"ouGuid\": \"19579bbf9-31d0-4548-b781f-ea4392b\"\n	}\n}', '返回参数\n{\n	\"custom\": [{\n		\"cs\": 筛选条件,\n		\"ss\": 是否多值,\n		\"searchField\": 查询字段,\n		\"name\": 标签名称,\n		\"alias\": 标签别名,\n		\"codevalues\": 关联代码项,\n		\"fs\": \"是否全文检索:1:是,其他:否\" \n	}\n],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": [{\n		\"cs\": \"0\",\n		\"ss\": \"\",\n		\"searchField\": \"name;name_tx;name_py\",\n		\"name\": \"姓名\",\n		\"alias\": \"rowguid\",\n		\"codevalues\": {},\n		\"fs\": \"1\"\n	},{\n		\"cs\": \"1\",\n		\"ss\": \"\",\n		\"searchField\": \"sex\",\n		\"name\": \"性别\",\n		\"alias\": \"sex\",\n		\"codevalues\": {\n			\"1\": \"男\",\n			\"2\": \"女\"\n		},\n		\"fs\": \"1\"\n	}, {\n		\"cs\": \"0\",\n		\"ss\": \"\",\n		\"searchField\": \"time1\",\n		\"name\": \"时间数据1\",\n		\"alias\": \"time1\",\n		\"codevalues\": {},\n		\"fs\": \"1\"\n	}, {\n		\"cs\": \"0\",\n		\"ss\": \"\",\n		\"searchField\": \"time2\",\n		\"name\": \"时间数据2\",\n		\"alias\": \"time2\",\n		\"codevalues\": {},\n		\"fs\": \"1\"\n	}, {\n		\"cs\": \"0\",\n		\"ss\": \"1\",\n		\"searchField\": \"xqhh\",\n		\"name\": \"兴趣爱好\",\n		\"alias\": \"xqhh\",\n		\"codevalues\": {\n			\"01\": \"唱\",\n			\"02\": \"跳\",\n			\"03\": \"rap\",\n			\"04\": \"篮球\"\n		},\n		\"fs\": \"1\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回失败描述\n\n{\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/getTagList', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 15:02:44', '2020-06-23 20:35:24');
            INSERT INTO `portrait_tags_api_info` VALUES ('4f4fb4ef-65d4-4415-a151-84e258295dc6', '4e026be2-a2aa-49f4-af1f-614070906a00', '获取自定义标签', '查询主体的自定义标签', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n		\"pageNum\": 1,\n		\"pageSize\": 1,\n                \"ouGuid\": \"19579bbf9-31d0-4548-b781f\"\n	}\n}', '返回参数\n{\n	\"custom\": {\n		\"result\": [{\n			\"tagname\": \"标签名称\",\n			\"subalias\": \"主体别名\",\n			\"subname\": 主体名称,\n			\"tagalias\": \"标签别名\",\n			\"guidname\": \"标签名称\",\n			\"codevalues\": 关联代码项,\n			\"typename\": \"标签分类名称\"\n		}\n],\n		\"count\": 2\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"result\": [{\n			\"tagname\": \"自定义描述\",\n			\"subalias\": \"TESTP\",\n			\"subname\": \"测试人\",\n			\"tagalias\": \"describe\",\n			\"guidname\": \"姓名\",\n			\"codevalues\": {},\n			\"typename\": \"自定义信息\"\n		}, {\n			\"tagname\": \"自定义外貌\",\n			\"subalias\": \"TESTP\",\n			\"subname\": \"测试人\",\n			\"tagalias\": \"face\",\n			\"guidname\": \"姓名\",\n			\"codevalues\": {},\n			\"typename\": \"自定义信息\"\n		}],\n		\"count\": 2\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/getCustomTags', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 07:03:18', '2020-06-23 20:49:34');
            INSERT INTO `portrait_tags_api_info` VALUES ('51408c9c-1b3d-4c1c-8fac-89f11ab3a4b3', '4e026be2-a2aa-49f4-af1f-614070906a00', '主体所含标签列表层级结构查询服务', '获取对应指标层级结构', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n                \"ouGuid\": \"19579bbf9-31d0-4548-b781f-ea4\"\n	}\n}', '返回参数描述:\n{\n	\"custom\": {\n		\"主键信息\": [{\n			\"cs\":筛选条件,\n			\"ss\":是否多值,\n			\"searchField\":查询字段,\n			\"name\":标签名称,\n			\"alias\": 标签别名,\n			\"codevalues\": 关联代码项,\n			\"fs\": 是否全文检索\n		}]\n      ….\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回成功描述\n{\n	\"custom\": {\n		\"主键信息\": [{\n			\"cs\": \"0\",\n			\"ss\": \"\",\n			\"searchField\": \"name;name_tx;name_py\",\n			\"name\": \"姓名\",\n			\"alias\": \"rowguid\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}],\n		\"扩展信息\": [{\n			\"cs\": \"1\",\n			\"ss\": \"\",\n			\"searchField\": \"number\",\n			\"name\": \"数量统计\",\n			\"alias\": \"number\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"1\",\n			\"ss\": \"\",\n			\"searchField\": \"pwlength\",\n			\"name\": \"密码长度\",\n			\"alias\": \"pwlength\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"0\",\n			\"ss\": \"1\",\n			\"searchField\": \"xqhh\",\n			\"name\": \"兴趣爱好\",\n			\"alias\": \"xqhh\",\n			\"codevalues\": {\n				\"01\": \"唱\",\n				\"02\": \"跳\",\n				\"03\": \"rap\",\n				\"04\": \"篮球\"\n			},\n			\"fs\": \"1\"\n		}],\n		\"基本信息\": [{\n			\"cs\": \"1\",\n			\"ss\": \"\",\n			\"searchField\": \"password\",\n			\"name\": \"密码\",\n			\"alias\": \"password\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"0\",\n			\"ss\": \"\",\n			\"searchField\": \"pingyin_tx;pingyin_py\",\n			\"name\": \"拼音内容\",\n			\"alias\": \"pingyin\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"1\",\n			\"ss\": \"\",\n			\"searchField\": \"sex\",\n			\"name\": \"性别\",\n			\"alias\": \"sex\",\n			\"codevalues\": {\n				\"1\": \"男\",\n				\"2\": \"女\"\n			},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"0\",\n			\"ss\": \"\",\n			\"searchField\": \"time1\",\n			\"name\": \"时间数据1\",\n			\"alias\": \"time1\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}, {\n			\"cs\": \"0\",\n			\"ss\": \"\",\n			\"searchField\": \"time2\",\n			\"name\": \"时间数据2\",\n			\"alias\": \"time2\",\n			\"codevalues\": {},\n			\"fs\": \"1\"\n		}]\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n{\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/getTagsAndDirectory', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 14:39:43', '2020-06-23 20:36:29');
            INSERT INTO `portrait_tags_api_info` VALUES ('6b223f8a-e361-43cb-814f-06d4ea59f537', '4e026be2-a2aa-49f4-af1f-614070906a00', '获取主体自定义指标值', '获取当前部门目标主体所拥有权限的自定义指标的值，不存在或所有指标均无数据的主体会被忽略', 0, '', '1', '0', '{\n    \"params\": {\n        \"subAlias\": \"JSU_PERSON\",\n        \"entityGuids\": [\"320158199410090589\"],\n        \"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n    }\n}', '返回参数\n{\n    \"custom\":个体业务数据,\n    \"status\": {\n        \"code\": \"000000\",\n        \"text\": \"请求成功\"\n    }\n}\n\n返回成功描述\n{\n    \"custom\": [{\n        \"rowkey\": \"320158199410090589\",\n        \"deathdate\": \"2020-04-23 15:12:19\",\n        \"hobby\": \"\"\n    }],\n    \"status\": {\n        \"code\": \"000000\",\n        \"text\": \"请求成功\"\n    }\n}\n返回失败描述\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchLabelsCustom', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 05:11:25', '2020-06-23 20:50:31');
            INSERT INTO `portrait_tags_api_info` VALUES ('6f9283e1-eb3d-4774-ae77-8aa2937b2d0b', '4e026be2-a2aa-49f4-af1f-614070906a00', '插入更新自定义指标的值', '插入更新自定义指标的值', 0, '', '1', '0', '{\n	\"params\": {\n				\"subAlias\": \"JSU_PERSON\",\n				\"rowGuid\": \"320158199410090589\",\n				\"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n				\"modifyInfo\": {\n					\"name\": \"zyq123\"\n				}\n			}\n}', '返回成功描述\n{\n	\"custom\": \"success\",\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/upsertCustomTags', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 06:08:09', '2020-06-23 20:50:26');
            INSERT INTO `portrait_tags_api_info` VALUES ('8a378cda-8e3e-46bc-82bc-b97c98149961', '4e026be2-a2aa-49f4-af1f-614070906a00', '画像列表查询服务', '获取所有的画像名称、别名等信息', 0, '', '1', '0', NULL, '返回参数:\n{\n	\"custom\": [{\n		\"name\": \"画像名称\",\n		\"alias\": \"画像别名\"\n	}\n],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": [{\n		\"name\": \"好人\",\n		\"alias\": \"haoren\"\n	}, {\n		\"name\": \"人信息\",\n		\"alias\": \"renxinxi\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回失败描述\n{\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/getPortraitList', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 13:20:48', '2020-06-23 20:36:37');
            INSERT INTO `portrait_tags_api_info` VALUES ('9a7538bb-b8f8-4789-94ac-13054481c024', '4e026be2-a2aa-49f4-af1f-614070906a00', '分页查询画像', '分页查询画像', 0, '', '1', '0', '{\n	\"params\": {\n		\"portraitAlias\": \"renxinxi\",\n		\"pageNum\": 1,\n		\"pageSize\": 2,\n                \"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n	}\n}', '返回参数\n{\n	\"custom\": {\n		\"result\":画像业务数据,\n		\"count\": 3\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"result\": [{\n			\"number\": 1,\n			\"rowguid\": \"xb\"\n		}, {\n			\"number\": 1,\n			\"rowguid\": \"yyf\"\n		}],\n		\"count\": 3\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回失败描述\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/showPortraits', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 08:59:29', '2020-06-23 20:49:22');
            INSERT INTO `portrait_tags_api_info` VALUES ('a2c937d1-306b-4227-ac50-5bfae503cf0a', '4e026be2-a2aa-49f4-af1f-614070906a00', '全文检索条件分页查询', '全文检索条件分页查询', 0, '', '1', '0', '{\n    \"params\": {\n        \"wd\": \"王\",\n        \"subAlias\": \"JSU_PERSON\",\n        \"fields\": \"xm\",\n        \"reFields\": \"\",\n        \"pageNum\": 1,\n        \"pageSize\": 2,\n        \"condition\": {\n            \"xx\": [\"AB型\", \"A型\"],\n            \"whcd\": [\"博士\"]\n        },\n      \"ouGuid\": \"19579bbf9-31d0-4548-b781f-ea4392\"\n    }\n}', '返回参数\n{\n	\"custom\": {\n		\"result\":个体业务数据,\n		\"count\": 10000\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"result\": [{\n			\"SHENGGAO\": \"160~165厘米\",\n			\"ZZZLEI\": \"学位证\",\n			\"subAlias\": \"R_BIGDATA\",\n			\"XM\": \"王以\",\n			\"XZZ\": \"江苏省张家港市阳信路121号-12-8\",\n			\"WHCD\": \"小学      \",\n			\"ROWGUID\": \"320582198910038749\"\n		}, {\n			\"SHENGGAO\": \"160~165厘米\",\n			\"ZZZLEI\": \"党员证\",\n			\"subAlias\": \"R_BIGDATA\",\n			\"XM\": \"王哲\",\n			\"XZZ\": \"江苏省张家港市澄海一路48号-6-2\",\n			\"WHCD\": \"博士      \",\n			\"ROWGUID\": \"320582198910044145\"\n		}],\n		\"count\": 10000\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchNodeByConPageSize', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 02:28:43', '2020-06-23 17:28:43');
            INSERT INTO `portrait_tags_api_info` VALUES ('a5f566cb-6ce3-4c6f-9caa-5bc8c8338738', '4e026be2-a2aa-49f4-af1f-614070906a00', '查询主体下个体服务', '根据主体标识查询目标个体数据', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n		\"entityGuid\": \"zzp\",\n                \"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n	}\n}', '返回参数\n{\n	\"custom\": 个体数据,\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"number\": 1,\n		\"password\": \"123456\",\n		\"pwlength\": 6,\n		\"rowguid\": \"zzp\",\n		\"age\": \"25\\r\"\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchLabel', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 12:26:22', '2020-06-23 20:37:40');
            INSERT INTO `portrait_tags_api_info` VALUES ('b9875cfb-edd7-444e-b8fc-ef1f3188ad1c', '4e026be2-a2aa-49f4-af1f-614070906a00', '全文检索', '全文检索', 0, '', '1', '0', '{\n	\"params\": {\n\"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n		\"pn\": \"0\",\n		\"rn\": \"1\",\n		\"wd\": \"凤凰镇\",\n		\"fields\": \"sf;jgqx;gmsfhm;hjxz;cym;mz;xm;\",\n		\"subAlias\": \"SJGCR\",\n		\"cl\": 0,\n		\"terminal\": \"0\",\n		\"condition\": [{\n			\"equal\": null,\n			\"equalList\": [\"王?\"],\n			\"fieldName\": \"xm\",\n			\"isLike\": false,\n			\"likeType\": \"\",\n			\"notEqual\": null,\n			\"notEqualList\": []\n		}],\n		\"times\": [{\n			\"endTime\": \"1986-07-26 23:59:59\",\n			\"fieldName\": \"csrq\",\n			\"startTime\": \"1985-07-26 00:00:00\"\n		}],\n		\"statistics\": \"\",\n		\"unionCondition\": [],\n		\"accuracy\": 0,\n		\"noWd\": true,\n		\"isUseClickSort\": false,\n		\"cutIngore\": \"\"\n	}\n}', '返回参数:\n{\n	\"custom\": {\n		\"result\":业务数据，\n		\"count\": 符合查询条件的数据量\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"result\": [{\n			\"xx\": \"AB型\",\n			\"csrq\": \"1985-11-12 00:00:00\",\n			\"whcd\": \"博士\",\n			\"xmpy\": \"WangKun\",\n			\"gmsfhm\": \"320321198511122034\",\n			\"zjxy\": \"无\",\n			\"zylb\": \"工人\",\n			\"rowguid\": \"320321198511122034\",\n			\"subAlias\": \"SJGCR\",\n			\"sg\": 178,\n			\"zzmm\": \"群众\",\n			\"lxdh\": \"13912034246\",\n			\"rylx\": \"常住人口\",\n			\"byzk\": \"未服兵役\",\n			\"xb\": \"男\",\n			\"mz\": \"汉族\",\n			\"xzzxz\": \"凤凰镇范楼镇汪楼村4组266号\",\n			\"sgfl\": \"175厘米-180厘米\",\n			\"hyzk\": \"已婚\",\n			\"xm\": \"王坤\",\n			\"csd\": \"凤凰镇\",\n			\"xmpyjx\": \"WK\",\n			\"csqx\": \"凤凰镇\"\n		}],\n		\"count\": 4\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchNodeByFullText', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 01:30:09', '2020-06-23 19:30:09');
            INSERT INTO `portrait_tags_api_info` VALUES ('c14fa968-927d-48d7-8500-55afaf90b7e0', '4e026be2-a2aa-49f4-af1f-614070906a00', '获取主体名称和别名', '获取系统中所有的主体信息', 0, '', '1', '0', NULL, '返回参数\n{\n	\"custom\": [{\n		\"name\": \"主体名称\",\n		\"alias\": \"主体别名\",\n		\"index\": \"全文检索索引名称\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": [{\n		\"name\": \"标签主体_人_GA演示_DEMO\",\n		\"alias\": \"R_DEMO\",\n		\"index\": \"013\"\n	}, {\n		\"name\": \"标签主体_人（GA)\",\n		\"alias\": \"R_BIGDATA\",\n		\"index\": \"021\"\n	}, {\n		\"name\": \"投标人\",\n		\"alias\": \"ZTBBIGDATA_TBR\",\n		\"index\": \"027\"\n	}, {\n		\"name\": \"数据工厂_人\",\n		\"alias\": \"SJGCR\",\n		\"index\": \"035\"\n	}, {\n		\"name\": \"测试人\",\n		\"alias\": \"TESTP\",\n		\"index\": \"034\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n{\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000030\",\n		\"text\": \"服务内部错误!\"\n	}\n}', '', '/rest/portrait/getSubList', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 16:54:03', '2020-06-28 14:37:59');
            INSERT INTO `portrait_tags_api_info` VALUES ('c2a73164-0820-4f59-b24b-75c199c1d735', '4e026be2-a2aa-49f4-af1f-614070906a00', '根据主体标识查询画像', '根据主体标识查询画像', 0, '', '1', '0', '{\n	\"params\": {\n		\"portraitAlias\": \"TESTP\",\n		\"entityGuids\": [\"zzp\", \"xb\", \"123456\"],\n                \"ouGuid\": \"19579bbf9-31d0-4548-b781f-ea43\"\n	}\n}', '返回参数\n{\n	\"custom\":画像业务数据,\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": [{\n		\"number\": 1,\n		\"rowguid\": \"zzp\",\n		\"age\": \"25\\r\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回失败描述\n{\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/showPortrait', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 09:55:41', '2020-06-23 20:48:48');
            INSERT INTO `portrait_tags_api_info` VALUES ('d3e34462-e880-4670-aa69-c56cba7f479b', '4e026be2-a2aa-49f4-af1f-614070906a00', '主体查询服务', '查询多个主体信息', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n		\"entityGuids\": [\"zzp\", \"xb\", \"123456\"]\n	}\n}', '返回参数\n{\n	\"custom\":个体业务数据,\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": [{\n		\"number\": 1,\n		\"password\": \"123456\",\n		\"pwlength\": 6,\n		\"rowguid\": \"xb\",\n		\"age\": \"28\"\n	}, {\n		\"number\": 1,\n		\"password\": \"123456\",\n		\"pwlength\": 6,\n		\"rowguid\": \"zzp\",\n		\"age\": \"25\\r\"\n	}],\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/compareEntitys', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 10:42:36', '2020-06-23 20:44:41');
            INSERT INTO `portrait_tags_api_info` VALUES ('d49f0b5b-47d4-4ad8-bfe9-77e2412ead79', '4e026be2-a2aa-49f4-af1f-614070906a00', '全文检索统计值', '全文检索统计值，注意时间格式为yyyy-MM-dd HH:mm:ss', 0, '', '1', '0', '{\n	\"params\": {\n		\"wd\": \"凤凰镇\",\n		\"fields\": \"sf;jgqx;gmsfhm;hjxz;cym;mz;xm;\",\n		\"subAlias\": \"SJGCR\",\n		\"condition\": [{\n			\"equal\": null,\n			\"equalList\": [\"王?\"],\n			\"fieldName\": \"xm\",\n			\"isLike\": false,\n			\"likeType\": \"\",\n			\"notEqual\": null,\n			\"notEqualList\": []\n		}],\n		\"times\": [{\n			\"endTime\": \"1986-07-26 23:59:59\",\n			\"fieldName\": \"csrq\",\n			\"startTime\": \"1985-07-26 00:00:00\"\n		}],\n		\"statistics\": \"whcd;byzk\",\n		\"unionCondition\": [],\n		\"accuracy\": 0\n	}\n}', '返回参数\n{\n	\"custom\": {\n		\"统计字段\": [{\n			\"categorynum\": 统计字段值,\n			\"count\": 统计到的数量\n		}]\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"byzk_keyword\": [{\n			\"categorynum\": \"未服兵役\",\n			\"count\": \"4\"\n		}],\n		\"whcd_keyword\": [{\n			\"categorynum\": \"大专\",\n			\"count\": \"2\"\n		}, {\n			\"categorynum\": \"博士\",\n			\"count\": \"1\"\n		}, {\n			\"categorynum\": \"高中\",\n			\"count\": \"1\"\n		}]\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchStat', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 04:18:52', '2020-06-23 20:58:26');
            INSERT INTO `portrait_tags_api_info` VALUES ('ef4d3843-7bad-42e5-a2c9-ddd7a43adceb', '4e026be2-a2aa-49f4-af1f-614070906a00', '全文检索分页查询', '全文检索分页查询', 0, '', '1', '0', '{\n    \"params\": {\n        \"wd\": \"王\",\n        \"subAlias\": \"JSU_PERSON\",\n        \"fields\": \"name\",\n        \"reFields\": \"\",\n        \"pageNum\": 1,\n        \"pageSize\": 10,\n        \"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n    }\n}', '返回参数\n{\n	\"custom\": {\n		\"result\":业务数据,\n		\"count\": 616\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n返回成功描述\n{\n	\"custom\": {\n		\"result\": [{\n			\"xx\": \"O型\",\n			\"csrq\": \"1985-04-05 00:00:00\",\n			\"whcd\": \"高中\",\n			\"xmpy\": \"WangMiaoMiao\",\n			\"gmsfhm\": \"320321198504050845\",\n			\"zjxy\": \"无\",\n			\"zylb\": \"农民\",\n			\"rowguid\": \"320321198504050845\",\n			\"subAlias\": \"SJGCR\",\n			\"sg\": 178,\n			\"zzmm\": \"群众\",\n			\"lxdh\": \"15851128533\",\n			\"rylx\": \"常住人口\",\n			\"byzk\": \"未服兵役\",\n			\"xb\": \"女\",\n			\"mz\": \"汉族\",\n			\"xzzxz\": \"乐余镇新沟镇新沟村十组8号\",\n			\"sgfl\": \"175厘米-180厘米\",\n			\"hyzk\": \"已婚\",\n			\"xm\": \"王苗苗\",\n			\"csd\": \"乐余镇\",\n			\"xmpyjx\": \"WMM\",\n			\"csqx\": \"乐余镇\"\n		}],\n		\"count\": 616\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchNodeByPageSize', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 03:24:32', '2020-06-23 20:59:25');
            INSERT INTO `portrait_tags_api_info` VALUES ('fc8f0e0b-551d-4c04-ad48-c00d4f825e3b', '4e026be2-a2aa-49f4-af1f-614070906a00', '个体查询服务', '根据个体标识查询个体层级结构和标签值', 0, '', '1', '0', '{\n	\"params\": {\n		\"subAlias\": \"TESTP\",\n		\"entityGuid\": \"320582193409230881\",\n                \"ouGuid\": \"9579bbf9-31d0-4548-b781f-ea4392bf68\"\n	}\n}', '返回参数:\n{\n	\"custom\": {\n		\"标签分类\": [{\n			\"name\": \"标签名称\",\n			\"alias\": \"标签别名\",\n			\"value\": 标签值   \"\n		}]\n]\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回成功描述\n{\n	\"custom\": {\n		\"学历职称\": [{\n			\"name\": \"文化程度\",\n			\"alias\": \"WHCD\",\n			\"value\": \"博士后    \"\n		}],\n		\"外貌特征\": [{\n			\"name\": \"发色\",\n			\"alias\": \"FAX\",\n			\"value\": \"\"\n		}, {\n			\"name\": \"身高\",\n			\"alias\": \"SHENGGAO\",\n			\"value\": \"175厘米以上\"\n		}, {\n			\"name\": \"体型\",\n			\"alias\": \"TX\",\n			\"value\": \"\"\n		}],\n		\"通讯信息\": [{\n			\"name\": \"Email\",\n			\"alias\": \"EMAIL\",\n			\"value\": \"\"\n		}, {\n			\"name\": \"QQ\",\n			\"alias\": \"QQ\",\n			\"value\": \"\"\n		}, {\n			\"name\": \"手机\",\n			\"alias\": \"SHOUJI\",\n			\"value\": \"\"\n		}],\n		\"身份属性\": [{\n			\"name\": \"身份\",\n			\"alias\": \"SHENFEN\",\n			\"value\": \"\"\n		}],\n		\"自然属性\": [{\n			\"name\": \"民族\",\n			\"alias\": \"MZ\",\n			\"value\": \"\"\n		}],\n		\"前科劣迹\": [{\n			\"name\": \"侵财\",\n			\"alias\": \"QINGCAI\",\n			\"value\": \"\"\n		}],\n		\"持有证件\": [{\n			\"name\": \"证件种类\",\n			\"alias\": \"ZZZLEI\",\n			\"value\": \"居住证\"\n		}],\n		\"宗教信仰\": [{\n			\"name\": \"宗教信仰\",\n			\"alias\": \"ZJXY\",\n			\"value\": \"\"\n		}],\n		\"基本信息\": [{\n			\"name\": \"身份证标签\",\n			\"alias\": \"ROWGUID\",\n			\"value\": \"320582193409230881\"\n		}, {\n			\"name\": \"姓名\",\n			\"alias\": \"XM\",\n			\"value\": \"王锦黛\"\n		}],\n		\"职业特点\": [{\n			\"name\": \"职业\",\n			\"alias\": \"ZHIYE\",\n			\"value\": \"\"\n		}],\n		\"地址信息\": [{\n			\"name\": \"户籍地址\",\n			\"alias\": \"HUJIDZ\",\n			\"value\": \"\"\n		}, {\n			\"name\": \"现住址\",\n			\"alias\": \"XZZ\",\n			\"value\": \"江苏省张家港市大港纬四街99号-13-6\"\n		}]\n	},\n	\"status\": {\n		\"code\": \"000000\",\n		\"text\": \"请求成功\"\n	}\n}\n\n返回失败描述\n\n  {\n	\"custom\": \"\",\n	\"status\": {\n		\"code\": \"000010\",\n		\"text\": \"参数错误!\"\n	}\n}', '', '/rest/portrait/searchLabels', 0, '', NULL, NULL, NULL, NULL, '2020-06-23 11:32:53', '2020-06-23 20:44:24');
     end if;
end;
GO
call epoint_proc_alter();
GO
drop procedure if exists `epoint_proc_alter`;
GO

-- DELIMITER ; --