drop procedure if exists`epoint_proc_alter`;
GO
create   procedure `epoint_proc_alter`()
begin
     if  (SELECT count( 1 ) FROM	information_schema.COLUMNS WHERE	TABLE_SCHEMA = DATABASE ( ) AND table_name = 'cockpit_norm_history_version' )<1
     then 
     	CREATE TABLE `cockpit_norm_history_version` (
  `RowGuid` varchar(50) NOT NULL,
  `NormDomain` varchar(10) DEFAULT NULL,
  `NormName` varchar(100) DEFAULT NULL,
  `NormType` varchar(50) DEFAULT NULL,
  `LastUpdateTime` datetime DEFAULT NULL,
  `Status` varchar(10) DEFAULT NULL,
  `Remark` longtext,
  `DataTableGuid` varchar(50) DEFAULT NULL,
  `DataFieldGuid` text,
  `DataFieldNameCN` text,
  `DataFieldNameEN` text,
  `GroupbyType` varchar(50) DEFAULT NULL,
  `TimeFieldGuid` varchar(50) DEFAULT NULL,
  `DimTableGuid` varchar(50) DEFAULT NULL,
  `DimFieldGuid` varchar(50) DEFAULT NULL,
  `DimFieldNameCN` varchar(50) DEFAULT NULL,
  `DimFieldNameEN` varchar(50) DEFAULT NULL,
  `RelateList` longtext,
  `FilterList` longtext,
  `GenerateSql` longtext,
  `TimeWindow` varchar(10) DEFAULT NULL,
  `NormBoid` varchar(50) DEFAULT NULL,
  `NormUrl` varchar(50) DEFAULT NULL,
  `NormChartType` varchar(50) DEFAULT NULL,
  `DataTableNameCN` varchar(50) DEFAULT NULL,
  `DataTableNameEN` varchar(50) DEFAULT NULL,
  `DimTableNameCN` varchar(50) DEFAULT NULL,
  `DimTableNameEN` varchar(50) DEFAULT NULL,
  `IsNeedWarning` varchar(10) DEFAULT NULL,
  `OrderNum` int(11) DEFAULT NULL,
  `CreateTime` datetime DEFAULT NULL,
  `CreateUserGuid` varchar(50) DEFAULT NULL,
  `SubscribeCount` int(11) DEFAULT '0',
  `CollectCount` int(11) DEFAULT '0',
  `LikeCount` int(11) DEFAULT '0',
  `ShareCount` int(11) DEFAULT '0',
  `CommentCount` int(11) DEFAULT '0',
  `SearchCount` int(11) DEFAULT '0',
  `DetailCount` int(11) DEFAULT '0',
  `TimeFieldNameCN` varchar(50) DEFAULT NULL,
  `TimeFieldNameEN` varchar(50) DEFAULT NULL,
  `Normanchor` varchar(50) DEFAULT NULL,
  `datasourcesys` varchar(50) DEFAULT NULL,
  `liableperson` varchar(50) DEFAULT NULL,
  `liableou` varchar(50) DEFAULT NULL,
  `lastupdatedate` datetime DEFAULT NULL,
  `datasourceid` varchar(50) DEFAULT NULL,
  `dimdatasourceid` varchar(50) DEFAULT NULL,
  `tasktiming` varchar(5) DEFAULT NULL,
  `intervalseconds` varchar(50) DEFAULT NULL,
  `intervalminutes` varchar(50) DEFAULT NULL,
  `hour` varchar(50) DEFAULT NULL,
  `minutes` varchar(50) DEFAULT NULL,
  `weekday` varchar(50) DEFAULT NULL,
  `dayofmonth` varchar(50) DEFAULT NULL,
  `xxljobid` varchar(50) DEFAULT NULL,
  `configtype` varchar(5) DEFAULT NULL,
  `dimtableguid2` varchar(50) DEFAULT NULL,
  `dimfieldguid2` varchar(50) DEFAULT NULL,
  `dimfieldnamecn2` varchar(50) DEFAULT NULL,
  `dimfieldnameen2` varchar(50) DEFAULT NULL,
  `dimtablenameen2` varchar(50) DEFAULT NULL,
  `dimtablenamecn2` varchar(50) DEFAULT NULL,
  `datatableguid2` varchar(50) DEFAULT NULL,
  `datatablenamecn2` varchar(50) DEFAULT NULL,
  `datatablenameen2` varchar(50) DEFAULT NULL,
  `datafieldguid2` varchar(50) DEFAULT NULL,
  `datafieldnamecn2` varchar(50) DEFAULT NULL,
  `datafieldnameen2` varchar(50) DEFAULT NULL,
  `sortOrder` varchar(10) DEFAULT NULL,
  `statisticsCycle` varchar(5) DEFAULT NULL,
  `isCumsum` varchar(5) DEFAULT NULL,
  `resultCount` int(11) DEFAULT NULL,
  `sortColumn` varchar(100) DEFAULT NULL,
  `rightControl` varchar(5) DEFAULT '0',
  `rightControlField` varchar(50) DEFAULT NULL,
  `rightControlFieldNameEn` varchar(50) DEFAULT NULL,
  `rightControlFieldFieldNameCn` varchar(50) DEFAULT NULL,
  `isOpen` varchar(10) DEFAULT NULL,
  `apiguid` varchar(100) DEFAULT NULL,
  `apiparams` text,
  `apifilter` varchar(100) DEFAULT NULL,
  `matchmap` varchar(100) DEFAULT NULL,
  `apiresult` text,
  `operateType` int(11) DEFAULT '0',
  `historyVersion` varchar(50) DEFAULT NULL,
  `normguid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`RowGuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
	end if;
end;
GO
call epoint_proc_alter();
GO
drop procedure if exists `epoint_proc_alter`;
GO